//
//  iconMapping.swift
//  KyoNeo
//
//  Created by Aether on 24/08/2023.
//

import SwiftUI

let iconMapping: [String: String] = [
    "Computer": "pc",
    "Comp": "pc",
    "Science": "flask",
    "Sci": "flask",
    "Mathematics": "function",
    "Math": "function",
    "Biology": "atom",
    "Bio": "atom",
    "Chemistry": "flask",
    "Chem": "flask",
    "Physics": "atom",
    "Phys": "atom",
    "History": "book.closed",
    "Hist": "book.closed",
    "English": "textformat",
    "Eng": "textformat",
    "Literature": "textformat",
    "Lit": "textformat",
    "Physical": "gym.bag",
    "Education": "graduationcap",
    "Educ": "graduationcap",
    "Business": "briefcase",
    "Bus": "briefcase",
    "Studies": "book.pages",
    "Stud": "book.pages",
    "Geography": "globe",
    "Geo": "globe",
    "Foreign": "globe.americas",
    "For": "globe.americas",
    "Language": "globe.asia.australia",
    "Lang": "globe.asia.australia",
    "Art": "paintpalette",
    "Environmental": "leaf",
    "Env": "leaf",
    "Political": "globe.europe.africa",
    "Pol": "globe.europe.africa",
    "Economics": "percent",
    "Econ": "percent",
    "Psychology": "brain",
    "Psych": "brain",
    "Sociology": "people.2",
    "Soc": "people.2",
    "Philosophy": "quote.bubble",
    "Phil": "quote.bubble",
    "Anthropology": "globe",
    "Anthro": "globe",
    "Engineering": "wrench.and.screwdriver",
    "Architecture": "building.2",
    "Arch": "building.2",
    "Marketing": "megaphone",
    "Mktg": "megaphone",
    "Journalism": "newspaper",
    "Journ": "newspaper",
    "Music": "music.note",
    "Theory": "music.note",
    "Theor": "music.note",
    "Drama": "theatermasks",
    "Dram": "theatermasks",
    "Creative": "paintbrush",
    "Creat": "paintbrush",
    "Writing": "pencil",
    "Writ": "pencil",
    "Statistics": "chart.pie",
    "Stat": "chart.pie",
    "Information": "info.circle",
    "Info": "info.circle",
    "Technology": "cpu",
    "Tech": "cpu",
    "Data": "archivebox",
    "Graphic": "paintpalette",
    "Graph": "paintpalette",
    "Design": "pencil.and.ellipsis.rectangle",
    "Des": "pencil.and.ellipsis.rectangle",
    "Organic": "leaf",
    "Org": "leaf",
    "Microbiology": "microscope",
    "Micro": "microscope",
    "Human": "person",
    "Hum": "person",
    "Anatomy": "heart",
    "Intl": "globe.asia.australia",
    "Relations": "globe.asia.australia",
    "Linear": "function",
    "Lin": "function",
    "Algebra": "xmark.rectangle",
    "Alg": "xmark.rectangle",
    "Multivariable": "function",
    "Multi": "function",
    "Calculus": "divide.circle",
    "Calc": "divide.circle",
    "Structures": "building.columns",
    "Struct": "building.columns",
    "Artificial": "cpu",
    "Artif": "cpu",
    "Intelligence": "cpu",
    "Intel": "cpu",
    "Machine": "cpu",
    "Mach": "cpu",
    "Learning": "brain",
    "Learn": "brain",
    "Operating": "cpu",
    "Oper": "cpu",
    "Systems": "desktopcomputer",
    "Sys": "desktopcomputer",
    "Database": "archivebox",
    "DB": "archivebox",
    "Management": "briefcase",
    "Mgmt": "briefcase",
    "Object-Oriented": "puzzlepiece",
    "OOP": "puzzlepiece",
    "Programming": "keyboard",
    "Prog": "keyboard",
    "Web": "globe",
    "Development": "wrench.and.hammer",
    "Dev": "wrench.and.hammer",
    "Mobile": "smartphone",
    "Mob": "smartphone",
    "App": "apps.iphone",
    "Network": "network",
    "Security": "shield.lefthalf.fill",
    "Sec": "shield.lefthalf.fill",
    "Human-Computer": "hand.tap",
    "HCI": "hand.tap",
    "Interaction": "hand.tap",
    "Interact": "hand.tap",
    "Project": "folder.badge.gearshape",
    "Proj": "folder.badge.gearshape",
    "Financial": "dollarsign.circle",
    "Fin": "dollarsign.circle",
    "Accounting": "list.bullet.rectangle",
    "Acc": "list.bullet.rectangle",
    "Corporate": "building.columns",
    "Corp": "building.columns",
    "Finance": "dollarsign.square",
    "Investments": "arrow.up.square",
    "Invest": "arrow.up.square",
    "Organizational": "people.2",
    "Behavior": "person",
    "Behav": "person",
    "Strategic": "chart.pie",
    "Strat": "chart.pie",
    "Cultural": "book.closed",
    "Cult": "book.closed",
    "Comparative": "arrow.left.arrow.right.square",
    "Politics": "globe.europe.africa",
    "Behavioral": "person",
    "Quantitative": "percent",
    "Quant": "percent",
    "Research": "doc.text",
    "Res": "doc.text",
    "Methods": "square.and.pencil",
    "Meth": "square.and.pencil",
    "Qualitative": "text.bubble",
    "Qual": "text.bubble",
    "Software": "archivebox",
    "Soft": "archivebox",
]

func getIconForClassName(_ className: String) -> String {
    let firstWord = className.components(separatedBy: " ")[0]

    if let iconName = iconMapping[firstWord] {
        return iconName
    } else {
        // Check for partial matches in the class names and abbreviations
        for (name, iconName) in iconMapping {
            if className.lowercased().contains(name.lowercased()) {
                return iconName
            }
        }

        // Return a default icon if no matching mapping is found
        return "book"
    }
}


